server {
    listen 80;
    server_name drawndimension.com www.drawndimension.com;
    return 301 https://www.drawndimension.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name drawndimension.com;

    ssl_certificate /etc/letsencrypt/live/drawndimension.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/drawndimension.com/privkey.pem;

    return 301 https://www.drawndimension.com$request_uri;
}

server {
    listen 443 ssl http2;
    server_name www.drawndimension.com;

    root /var/www/vhosts/drawndimension.com/public_html;
    index index.html;

    ssl_certificate /etc/letsencrypt/live/drawndimension.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/drawndimension.com/privkey.pem;

    location = /robots.txt {
        try_files $uri =404;
    }

    location = /sitemap.xml {
        try_files $uri =404;
    }

    location /media/ {
        proxy_pass https://api.drawndimension.com/media/;
        proxy_set_header Host api.drawndimension.com;
        proxy_ssl_server_name on;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
