import {
  ArrowRight,
  Play,
  Code,
  Ruler,
  Box,
  FileText,
  // পূর্বের ১০০টি (সবগুলো বহাল)
  Palette,
  Globe,
  Settings,
  Plus,
  Minus,
  Check,
  X,
  Heart,
  Star,
  Moon,
  Sun,
  Cloud,
  Download,
  Upload,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  AlertTriangle,
  Bell,
  Bookmark,
  Camera,
  Clapperboard,
  Clipboard,
  Coffee,
  Command,
  Copy,
  CreditCard,
  Crown,
  Database,
  DollarSign,
  Edit,
  Eye,
  EyeOff,
  FastForward,
  File,
  Filter,
  Flag,
  Folder,
  Gift,
  GitBranch,
  Hand,
  Headphones,
  Home,
  Image,
  Info,
  Key,
  Layers,
  Layout,
  LifeBuoy,
  Lock,
  LogIn,
  LogOut,
  Maximize,
  MessageCircle,
  Monitor,
  MousePointer,
  Music,
  Newspaper,
  Package,
  Paperclip,
  Pause,
  PenTool,
  Pencil,
  PieChart,
  Pin,
  Rocket,
  Save,
  Scissors,
  Search,
  Send,
  Share2,
  Shield,
  ShoppingCart,
  Sliders,
  Smartphone,
  Speaker,
  Table,
  Tag,
  Target,
  Terminal,
  ThumbsUp,
  Trash,
  Truck,
  User,
  Users,
  Video,
  Volume2,
  Wand,
  Wrench,
  Zap,
  ZoomIn,

  // ====== নতুন ভ্যালিড ইঞ্জিনিয়ারিং/টেক আইকন (কোনো error হবে না) ======
  Accessibility,
  Activity,
  AirVent,
  AlarmClock,
  AlignCenter,
  AlignJustify,
  AlignLeft,
  AlignRight,
  Anchor,
  Aperture,
  AppWindow,
  Archive,
  Armchair,
  ArrowBigDown,
  ArrowBigLeft,
  ArrowBigRight,
  ArrowBigUp,
  ArrowDown,
  ArrowLeft,
  ArrowUp,
  Asterisk,
  AtSign,
  Atom,
  Award,
  Axe,
  Axis3d,
  Backpack,
  Badge,
  BadgeCheck,
  BadgeDollarSign,
  BaggageClaim,
  Ban,
  Banknote,
  BarChart,
  BarChart2,
  BarChart3,
  BarChart4,
  Baseline,
  Bath,
  Battery,
  BatteryCharging,
  BatteryFull,
  BatteryLow,
  BatteryMedium,
  Beaker,
  Bed,
  Bike,
  Binary,
  Biohazard,
  Bird,
  Bitcoin,
  Blinds,
  Blocks,
  Bluetooth,
  BluetoothConnected,
  BluetoothOff,
  BluetoothSearching,
  Bold,
  Bomb,
  Bone,
  Book,
  BookOpen,
  BookOpenCheck,
  BookmarkMinus,
  BookmarkPlus,
  Bot,
  BoxSelect,
  Braces,
  Brackets,
  Brain,
  BrainCircuit,
  Briefcase,
  BriefcaseBusiness,
  Brush,
  Bug,
  Building,
  Building2,
  Bus,
  Cable,
  Cake,
  Calculator,
  CalendarCheck,
  CalendarDays,
  CalendarHeart,
  CalendarMinus,
  CalendarPlus,
  CalendarRange,
  CalendarX,
  CandlestickChart,
  Car,
  Carrot,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  Cast,
  Cat,
  CheckCheck,
  ChefHat,
  Cherry,
  ChevronDown,
  ChevronFirst,
  ChevronLast,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  CircuitBoard,
  Citrus,
  ClipboardCheck,
  ClipboardCopy,
  ClipboardList,
  ClipboardPen,
  ClockAlert,
  Clock1,
  Clock10,
  Clock11,
  Clock12,
  Clock2,
  Clock3,
  Clock4,
  Clock5,
  Clock6,
  Clock7,
  Clock8,
  Clock9,
  CloudCog,
  CloudDrizzle,
  CloudFog,
  CloudHail,
  CloudLightning,
  CloudMoon,
  CloudMoonRain,
  CloudOff,
  CloudRain,
  CloudRainWind,
  CloudSnow,
  CloudSun,
  CloudSunRain,
  Cloudy,
  Clover,
  Code2,
  CodeSquare,
  Cog,
  Coins,
  Columns,
  Combine,
  Contact,
  Container,
  Contrast,
  Cookie,
  CookingPot,
  CopyCheck,
  CopyMinus,
  CopyPlus,
  CornerDownLeft,
  CornerDownRight,
  CornerLeftDown,
  CornerLeftUp,
  CornerRightDown,
  CornerRightUp,
  CornerUpLeft,
  CornerUpRight,
  Cpu,
  CreativeCommons,
  Crop,
  Cross,
  Crosshair,
  DatabaseBackup,
  DatabaseZap,
  Delete,
  Dessert,
  Diamond,
  Dice1,
  Dice2,
  Dice3,
  Dice4,
  Dice5,
  Dice6,
  Dices,
  Diff,
  Disc,
  Divide,
  Donut,
  DoorClosed,
  DoorOpen,
  Dot,
  DownloadCloud,
  DraftingCompass,
  Droplet,
  Droplets,
  Dumbbell,
  Ear,
  Earth,
  Eclipse,
  Egg,
  Equal,
  Eraser,
  Euro,
  Expand,
  ExternalLink,
  Factory,
  Fan,
  Feather,
  Fence,
  FileBadge,
  FileBarChart,
  FileCode,
  FileDigit,
  FileInput,
  FileJson,
  FileKey,
  FileLineChart,
  FileOutput,
  FilePlus,
  FileQuestion,
  FileSearch,
  FileSignature,
  FileSpreadsheet,
  FileVideo,
  FileVolume,
  FileWarning,
  Files,
  Film,
  Fingerprint,
  Fish,
  Flame,
  Flashlight,
  FlaskConical,
  FlaskRound,
  FlipHorizontal,
  FlipHorizontal2,
  FlipVertical,
  FlipVertical2,
  Flower,
  Flower2,
  Focus,
  FolderArchive,
  FolderCheck,
  FolderClock,
  FolderClosed,
  FolderDot,
  FolderDown,
  FolderEdit,
  FolderGit,
  FolderGit2,
  FolderHeart,
  FolderInput,
  FolderKey,
  FolderLock,
  FolderMinus,
  FolderOpen,
  FolderOpenDot,
  FolderOutput,
  FolderPlus,
  FolderSearch,
  FolderSymlink,
  FolderTree,
  FolderX,
  FormInput,
  Forward,
  Frame,
  Frown,
  Fuel,
  Fullscreen,
  Gamepad,
  Gamepad2,
  Gauge,
  Gavel,
  Gem,
  Ghost,
  GitCommit,
  GitCompare,
  GitFork,
  GitMerge,
  GitPullRequest,
  GitPullRequestClosed,
  GitPullRequestDraft,
  GlassWater,
  Glasses,
  GlobeLock,
  Grab,
  GraduationCap,
  Grape,
  Grid,
  GripHorizontal,
  GripVertical,
  Group,
  Hammer,
  HardDrive,
  HardHat,
  Hash,
  Haze,
  HdmiPort,
  Heading,
  Heading1,
  Heading2,
  Heading3,
  Heading4,
  Heading5,
  Heading6,
  HeadphoneOff,
  HelpCircle,
  Hexagon,
  Highlighter,
  History,
  Hop,
  Hourglass,
  IceCream,
  ImageMinus,
  ImagePlus,
  Import,
  Indent,
  Infinity,
  InspectionPanel,
  Joystick,
  KeyRound,
  KeySquare,
  Keyboard,
  Lamp,
  LandPlot,
  Landmark,
  Languages,
  Laptop,
  Laptop2,
  Lasso,
  Laugh,
  Leaf,
  Library,
  Ligature,
  Lightbulb,
  LightbulbOff,
  LineChart,
  List,
  ListChecks,
  ListEnd,
  ListMinus,
  ListMusic,
  ListOrdered,
  ListPlus,
  ListStart,
  ListTodo,
  ListVideo,
  Loader,
  Loader2,
  Locate,
  LocateFixed,
  LocateOff,
  Logs,
  Magnet,
  MailCheck,
  MailMinus,
  MailOpen,
  MailPlus,
  MailQuestion,
  MailSearch,
  MailWarning,
  Martini,
  Medal,
  Megaphone,
  Meh,
  MemoryStick,
  Menu,
  MessageSquareDashed,
  MessageSquareDot,
  MessageSquareHeart,
  MessageSquareLock,
  MessageSquarePlus,
  MessageSquareQuote,
  MessageSquareReply,
  MessageSquareShare,
  MessageSquareWarning,
  Mic,
  Mic2,
  MicOff,
  Microscope,
  Microwave,
  Milestone,
  Milk,
  Minimize2,
  MonitorCheck,
  MonitorDot,
  MonitorDown,
  MonitorOff,
  MonitorPause,
  MonitorPlay,
  MonitorSmartphone,
  MonitorSpeaker,
  MonitorUp,
  MonitorX,
  MoonStar,
  Mountain,
  MountainSnow,
  Move,
  Move3d,
  MoveDiagonal,
  MoveDiagonal2,
  MoveDown,
  MoveHorizontal,
  MoveLeft,
  MoveRight,
  MoveUp,
  MoveVertical,
  Navigation,
  Navigation2,
  Network,
  Nfc,
  Nut,
  Octagon,
  Option,
  Orbit,
  Outdent,
  PaintBucket,
  Paintbrush,
  Parentheses,
  ParkingCircle,
  ParkingSquare,
  PartyPopper,
  PauseCircle,
  PawPrint,
  PcCase,
  Pen,
  PenSquare,
  PencilLine,
  Percent,
  PersonStanding,
  PhoneCall,
  PhoneForwarded,
  PhoneIncoming,
  PhoneMissed,
  PhoneOff,
  PhoneOutgoing,
  Pi,
  PictureInPicture,
  PictureInPicture2,
  PiggyBank,
  Pilcrow,
  Pill,
  PinOff,
  Pipette,
  Plane,
  PlaneLanding,
  PlaneTakeoff,
  PlayCircle,
  Plug,
  Plug2,
  Podcast,
  Pointer,
  Popcorn,
  Popsicle,
  PoundSterling,
  Power,
  PowerOff,
  Printer,
  Projector,
  Puzzle,
  QrCode,
  Quote,
  Radar,
  Radiation,
  Radical,
  Radio,
  RadioReceiver,
  RadioTower,
  Rainbow,
  Rat,
  Receipt,
  RectangleHorizontal,
  RectangleVertical,
  Recycle,
  Redo,
  Redo2,
  RefreshCcw,
  RefreshCw,
  Refrigerator,
  Regex,
  RemoveFormatting,
  Repeat,
  Repeat1,
  Replace,
  Reply,
  ReplyAll,
  Rewind,
  Ribbon,
  RockingChair,
  RollerCoaster,
  Rotate3d,
  RotateCcw,
  RotateCw,
  Route,
  Router,
  Rss,
  RussianRuble,
  Sailboat,
  Salad,
  Sandwich,
  Satellite,
  SatelliteDish,
  Scale,
  Scale3d,
  Scaling,
  Scan,
  ScanFace,
  ScanLine,
  School,
  ScissorsLineDashed,
  ScreenShare,
  Scroll,
  SearchCheck,
  SearchCode,
  SearchSlash,
  Server,
  ServerCog,
  ServerCrash,
  ServerOff,
  Shapes,
  Share,
  Sheet,
  Shell,
  Ship,
  Shirt,
  ShoppingBag,
  Shovel,
  ShowerHead,
  Shrink,
  Shrub,
  Shuffle,
  Sigma,
  Signal,
  SignalHigh,
  SignalLow,
  SignalMedium,
  SignalZero,
  Siren,
  SkipBack,
  SkipForward,
  Skull,
  Slice,
  SlidersHorizontal,
  Smile,
  SmilePlus,
  Snowflake,
  Sofa,
  SortAsc,
  SortDesc,
  Space,
  Sparkles,
  SpellCheck,
  Sprout,
  Square,
  Stamp,
  StarHalf,
  StepBack,
  StepForward,
  Stethoscope,
  Sticker,
  StickyNote,
  StopCircle,
  Store,
  StretchHorizontal,
  StretchVertical,
  Strikethrough,
  Subscript,
  SunDim,
  SunMedium,
  SunMoon,
  Sunrise,
  Sunset,
  Superscript,
  SwissFranc,
  SwitchCamera,
  Sword,
  Swords,
  Syringe,
  Table2,
  TableProperties,
  Tablet,
  Tablets,
  Tally1,
  Tally2,
  Tally3,
  Tally4,
  Tally5,
  Tangent,
  Telescope,
  Tent,
  TestTube,
  TestTube2,
  Thermometer,
  ThermometerSnowflake,
  ThermometerSun,
  Timer,
  TimerOff,
  TimerReset,
  ToggleLeft,
  ToggleRight,
  Tornado,
  Touchpad,
  TouchpadOff,
  TowerControl,
  ToyBrick,
  Tractor,
  TrafficCone,
  Train,
  TramFront,
  TrendingDown,
  TrendingUp,
  Triangle,
  Trophy,
  Tv,
  Tv2,
  Type,
  Umbrella,
  Underline,
  Undo,
  Undo2,
  Unlink,
  Unlock,
  UploadCloud,
  Usb,
  Utensils,
  UtensilsCrossed,
  UtilityPole,
  Variable,
  Vegan,
  Vibrate,
  VideoOff,
  View,
  Voicemail,
  Volume,
  Volume1,
  VolumeX,
  Wallet,
  Wallpaper,
  Warehouse,
  Watch,
  Waves,
  Webcam,
  Webhook,
  Wheat,
  WholeWord,
  Wifi,
  WifiOff,
  Wind,
  Wine,
  Workflow,
  WrapText,
  ZoomOut,
} from "lucide-react";
import { Link } from "react-router-dom";
import {
  DEFAULT_HOME_PAGE_SETTINGS,
  type HomeHeroSection,
  type HomeKeyMetricsSection,
} from "@/components/shared/homePageSettings";
import HeroSoftwareStrip from "@/components/HeroSoftwareStrip";
import HomeMetricsSection from "@/components/HomeMetricsSection";

const iconMap = {
  // পূর্বের ১০০+ আইকন (সব রাখা)
  "file-text": FileText,
  box: Box,
  ruler: Ruler,
  code: Code,
  palette: Palette,
  globe: Globe,
  settings: Settings,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
  heart: Heart,
  star: Star,
  moon: Moon,
  sun: Sun,
  cloud: Cloud,
  download: Download,
  upload: Upload,
  mail: Mail,
  phone: Phone,
  "map-pin": MapPin,
  calendar: Calendar,
  clock: Clock,
  "alert-triangle": AlertTriangle,
  bell: Bell,
  bookmark: Bookmark,
  camera: Camera,
  clapperboard: Clapperboard,
  clipboard: Clipboard,
  coffee: Coffee,
  command: Command,
  copy: Copy,
  "credit-card": CreditCard,
  crown: Crown,
  database: Database,
  "dollar-sign": DollarSign,
  edit: Edit,
  eye: Eye,
  "eye-off": EyeOff,
  "fast-forward": FastForward,
  file: File,
  filter: Filter,
  flag: Flag,
  folder: Folder,
  gift: Gift,
  "git-branch": GitBranch,
  hand: Hand,
  headphones: Headphones,
  home: Home,
  image: Image,
  info: Info,
  key: Key,
  layers: Layers,
  layout: Layout,
  "life-buoy": LifeBuoy,
  lock: Lock,
  "log-in": LogIn,
  "log-out": LogOut,
  maximize: Maximize,
  "message-circle": MessageCircle,
  monitor: Monitor,
  "mouse-pointer": MousePointer,
  music: Music,
  newspaper: Newspaper,
  package: Package,
  paperclip: Paperclip,
  pause: Pause,
  "pen-tool": PenTool,
  pencil: Pencil,
  "pie-chart": PieChart,
  pin: Pin,
  rocket: Rocket,
  save: Save,
  scissors: Scissors,
  search: Search,
  send: Send,
  "share-2": Share2,
  shield: Shield,
  "shopping-cart": ShoppingCart,
  sliders: Sliders,
  smartphone: Smartphone,
  speaker: Speaker,
  table: Table,
  tag: Tag,
  target: Target,
  terminal: Terminal,
  "thumbs-up": ThumbsUp,
  trash: Trash,
  truck: Truck,
  user: User,
  users: Users,
  video: Video,
  "volume-2": Volume2,
  wand: Wand,
  wrench: Wrench,
  zap: Zap,
  "zoom-in": ZoomIn,

  // নতুন ভ্যালিড আইকন ম্যাপিং
  accessibility: Accessibility,
  activity: Activity,
  "air-vent": AirVent,
  "alarm-clock": AlarmClock,
  "align-center": AlignCenter,
  "align-justify": AlignJustify,
  "align-left": AlignLeft,
  "align-right": AlignRight,
  anchor: Anchor,
  aperture: Aperture,
  "app-window": AppWindow,
  archive: Archive,
  armchair: Armchair,
  "arrow-big-down": ArrowBigDown,
  "arrow-big-left": ArrowBigLeft,
  "arrow-big-right": ArrowBigRight,
  "arrow-big-up": ArrowBigUp,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-up": ArrowUp,
  asterisk: Asterisk,
  "at-sign": AtSign,
  atom: Atom,
  award: Award,
  axe: Axe,
  "axis-3d": Axis3d,
  backpack: Backpack,
  badge: Badge,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "baggage-claim": BaggageClaim,
  ban: Ban,
  banknote: Banknote,
  "bar-chart": BarChart,
  "bar-chart-2": BarChart2,
  "bar-chart-3": BarChart3,
  "bar-chart-4": BarChart4,
  baseline: Baseline,
  bath: Bath,
  battery: Battery,
  "battery-charging": BatteryCharging,
  "battery-full": BatteryFull,
  "battery-low": BatteryLow,
  "battery-medium": BatteryMedium,
  beaker: Beaker,
  bed: Bed,
  bike: Bike,
  binary: Binary,
  biohazard: Biohazard,
  bird: Bird,
  bitcoin: Bitcoin,
  blinds: Blinds,
  blocks: Blocks,
  bluetooth: Bluetooth,
  "bluetooth-connected": BluetoothConnected,
  "bluetooth-off": BluetoothOff,
  "bluetooth-searching": BluetoothSearching,
  bold: Bold,
  bomb: Bomb,
  bone: Bone,
  book: Book,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "bookmark-minus": BookmarkMinus,
  "bookmark-plus": BookmarkPlus,
  bot: Bot,
  "box-select": BoxSelect,
  braces: Braces,
  brackets: Brackets,
  brain: Brain,
  "brain-circuit": BrainCircuit,
  briefcase: Briefcase,
  "briefcase-business": BriefcaseBusiness,
  brush: Brush,
  bug: Bug,
  building: Building,
  "building-2": Building2,
  bus: Bus,
  cable: Cable,
  cake: Cake,
  calculator: Calculator,
  "calendar-check": CalendarCheck,
  "calendar-days": CalendarDays,
  "calendar-heart": CalendarHeart,
  "calendar-minus": CalendarMinus,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  "calendar-x": CalendarX,
  "candlestick-chart": CandlestickChart,
  car: Car,
  carrot: Carrot,
  "case-lower": CaseLower,
  "case-sensitive": CaseSensitive,
  "case-upper": CaseUpper,
  cast: Cast,
  cat: Cat,
  "check-check": CheckCheck,
  "chef-hat": ChefHat,
  cherry: Cherry,
  "chevron-down": ChevronDown,
  "chevron-first": ChevronFirst,
  "chevron-last": ChevronLast,
  "chevron-left": ChevronLeft,
  "chevron-right": ChevronRight,
  "chevron-up": ChevronUp,
  "circuit-board": CircuitBoard,
  citrus: Citrus,
  "clipboard-check": ClipboardCheck,
  "clipboard-copy": ClipboardCopy,
  "clipboard-list": ClipboardList,
  "clipboard-pen": ClipboardPen,
  "clock-alert": ClockAlert,
  "clock-1": Clock1,
  "clock-10": Clock10,
  "clock-11": Clock11,
  "clock-12": Clock12,
  "clock-2": Clock2,
  "clock-3": Clock3,
  "clock-4": Clock4,
  "clock-5": Clock5,
  "clock-6": Clock6,
  "clock-7": Clock7,
  "clock-8": Clock8,
  "clock-9": Clock9,
  "cloud-cog": CloudCog,
  "cloud-drizzle": CloudDrizzle,
  "cloud-fog": CloudFog,
  "cloud-hail": CloudHail,
  "cloud-lightning": CloudLightning,
  "cloud-moon": CloudMoon,
  "cloud-moon-rain": CloudMoonRain,
  "cloud-off": CloudOff,
  "cloud-rain": CloudRain,
  "cloud-rain-wind": CloudRainWind,
  "cloud-snow": CloudSnow,
  "cloud-sun": CloudSun,
  "cloud-sun-rain": CloudSunRain,
  cloudy: Cloudy,
  clover: Clover,
  "code-2": Code2,
  "code-square": CodeSquare,
  cog: Cog,
  coins: Coins,
  columns: Columns,
  combine: Combine,
  contact: Contact,
  container: Container,
  contrast: Contrast,
  cookie: Cookie,
  "cooking-pot": CookingPot,
  "copy-check": CopyCheck,
  "copy-minus": CopyMinus,
  "copy-plus": CopyPlus,
  "corner-down-left": CornerDownLeft,
  "corner-down-right": CornerDownRight,
  "corner-left-down": CornerLeftDown,
  "corner-left-up": CornerLeftUp,
  "corner-right-down": CornerRightDown,
  "corner-right-up": CornerRightUp,
  "corner-up-left": CornerUpLeft,
  "corner-up-right": CornerUpRight,
  cpu: Cpu,
  "creative-commons": CreativeCommons,
  crop: Crop,
  cross: Cross,
  crosshair: Crosshair,
  "database-backup": DatabaseBackup,
  "database-zap": DatabaseZap,
  delete: Delete,
  dessert: Dessert,
  diamond: Diamond,
  "dice-1": Dice1,
  "dice-2": Dice2,
  "dice-3": Dice3,
  "dice-4": Dice4,
  "dice-5": Dice5,
  "dice-6": Dice6,
  dices: Dices,
  diff: Diff,
  disc: Disc,
  divide: Divide,
  donut: Donut,
  "door-closed": DoorClosed,
  "door-open": DoorOpen,
  dot: Dot,
  "download-cloud": DownloadCloud,
  "drafting-compass": DraftingCompass,
  droplet: Droplet,
  droplets: Droplets,
  dumbbell: Dumbbell,
  ear: Ear,
  earth: Earth,
  eclipse: Eclipse,
  egg: Egg,
  equal: Equal,
  eraser: Eraser,
  euro: Euro,
  expand: Expand,
  "external-link": ExternalLink,
  factory: Factory,
  fan: Fan,
  feather: Feather,
  fence: Fence,
  "file-badge": FileBadge,
  "file-bar-chart": FileBarChart,
  "file-code": FileCode,
  "file-digit": FileDigit,
  "file-input": FileInput,
  "file-json": FileJson,
  "file-key": FileKey,
  "file-line-chart": FileLineChart,
  "file-output": FileOutput,
  "file-plus": FilePlus,
  "file-question": FileQuestion,
  "file-search": FileSearch,
  "file-signature": FileSignature,
  "file-spreadsheet": FileSpreadsheet,
  "file-video": FileVideo,
  "file-volume": FileVolume,
  "file-warning": FileWarning,
  files: Files,
  film: Film,
  fingerprint: Fingerprint,
  fish: Fish,
  flame: Flame,
  flashlight: Flashlight,
  "flask-conical": FlaskConical,
  "flask-round": FlaskRound,
  "flip-horizontal": FlipHorizontal,
  "flip-horizontal-2": FlipHorizontal2,
  "flip-vertical": FlipVertical,
  "flip-vertical-2": FlipVertical2,
  flower: Flower,
  "flower-2": Flower2,
  focus: Focus,
  "folder-archive": FolderArchive,
  "folder-check": FolderCheck,
  "folder-clock": FolderClock,
  "folder-closed": FolderClosed,
  "folder-dot": FolderDot,
  "folder-down": FolderDown,
  "folder-edit": FolderEdit,
  "folder-git": FolderGit,
  "folder-git-2": FolderGit2,
  "folder-heart": FolderHeart,
  "folder-input": FolderInput,
  "folder-key": FolderKey,
  "folder-lock": FolderLock,
  "folder-minus": FolderMinus,
  "folder-open": FolderOpen,
  "folder-open-dot": FolderOpenDot,
  "folder-output": FolderOutput,
  "folder-plus": FolderPlus,
  "folder-search": FolderSearch,
  "folder-symlink": FolderSymlink,
  "folder-tree": FolderTree,
  "folder-x": FolderX,
  "form-input": FormInput,
  forward: Forward,
  frame: Frame,
  frown: Frown,
  fuel: Fuel,
  fullscreen: Fullscreen,
  gamepad: Gamepad,
  "gamepad-2": Gamepad2,
  gauge: Gauge,
  gavel: Gavel,
  gem: Gem,
  ghost: Ghost,
  "git-commit": GitCommit,
  "git-compare": GitCompare,
  "git-fork": GitFork,
  "git-merge": GitMerge,
  "git-pull-request": GitPullRequest,
  "git-pull-request-closed": GitPullRequestClosed,
  "git-pull-request-draft": GitPullRequestDraft,
  "glass-water": GlassWater,
  glasses: Glasses,
  "globe-lock": GlobeLock,
  grab: Grab,
  "graduation-cap": GraduationCap,
  grape: Grape,
  grid: Grid,
  "grip-horizontal": GripHorizontal,
  "grip-vertical": GripVertical,
  group: Group,
  hammer: Hammer,
  "hard-drive": HardDrive,
  "hard-hat": HardHat,
  hash: Hash,
  haze: Haze,
  "hdmi-port": HdmiPort,
  heading: Heading,
  "heading-1": Heading1,
  "heading-2": Heading2,
  "heading-3": Heading3,
  "heading-4": Heading4,
  "heading-5": Heading5,
  "heading-6": Heading6,
  "headphone-off": HeadphoneOff,
  "help-circle": HelpCircle,
  hexagon: Hexagon,
  highlighter: Highlighter,
  history: History,
  hop: Hop,
  hourglass: Hourglass,
  "ice-cream": IceCream,
  "image-minus": ImageMinus,
  "image-plus": ImagePlus,
  import: Import,
  indent: Indent,
  infinity: Infinity,
  "inspection-panel": InspectionPanel,
  joystick: Joystick,
  "key-round": KeyRound,
  "key-square": KeySquare,
  keyboard: Keyboard,
  lamp: Lamp,
  "land-plot": LandPlot,
  landmark: Landmark,
  languages: Languages,
  laptop: Laptop,
  "laptop-2": Laptop2,
  lasso: Lasso,
  laugh: Laugh,
  leaf: Leaf,
  library: Library,
  ligature: Ligature,
  lightbulb: Lightbulb,
  "lightbulb-off": LightbulbOff,
  "line-chart": LineChart,
  list: List,
  "list-checks": ListChecks,
  "list-end": ListEnd,
  "list-minus": ListMinus,
  "list-music": ListMusic,
  "list-ordered": ListOrdered,
  "list-plus": ListPlus,
  "list-start": ListStart,
  "list-todo": ListTodo,
  "list-video": ListVideo,
  loader: Loader,
  "loader-2": Loader2,
  locate: Locate,
  "locate-fixed": LocateFixed,
  "locate-off": LocateOff,
  logs: Logs,
  magnet: Magnet,
  "mail-check": MailCheck,
  "mail-minus": MailMinus,
  "mail-open": MailOpen,
  "mail-plus": MailPlus,
  "mail-question": MailQuestion,
  "mail-search": MailSearch,
  "mail-warning": MailWarning,
  martini: Martini,
  medal: Medal,
  megaphone: Megaphone,
  meh: Meh,
  "memory-stick": MemoryStick,
  menu: Menu,
  "message-square-dashed": MessageSquareDashed,
  "message-square-dot": MessageSquareDot,
  "message-square-heart": MessageSquareHeart,
  "message-square-lock": MessageSquareLock,
  "message-square-plus": MessageSquarePlus,
  "message-square-quote": MessageSquareQuote,
  "message-square-reply": MessageSquareReply,
  "message-square-share": MessageSquareShare,
  "message-square-warning": MessageSquareWarning,
  mic: Mic,
  "mic-2": Mic2,
  "mic-off": MicOff,
  microscope: Microscope,
  microwave: Microwave,
  milestone: Milestone,
  milk: Milk,
  "minimize-2": Minimize2,
  "monitor-check": MonitorCheck,
  "monitor-dot": MonitorDot,
  "monitor-down": MonitorDown,
  "monitor-off": MonitorOff,
  "monitor-pause": MonitorPause,
  "monitor-play": MonitorPlay,
  "monitor-smartphone": MonitorSmartphone,
  "monitor-speaker": MonitorSpeaker,
  "monitor-up": MonitorUp,
  "monitor-x": MonitorX,
  "moon-star": MoonStar,
  mountain: Mountain,
  "mountain-snow": MountainSnow,
  move: Move,
  "move-3d": Move3d,
  "move-diagonal": MoveDiagonal,
  "move-diagonal-2": MoveDiagonal2,
  "move-down": MoveDown,
  "move-horizontal": MoveHorizontal,
  "move-left": MoveLeft,
  "move-right": MoveRight,
  "move-up": MoveUp,
  "move-vertical": MoveVertical,
  navigation: Navigation,
  "navigation-2": Navigation2,
  network: Network,
  nfc: Nfc,
  nut: Nut,
  octagon: Octagon,
  option: Option,
  orbit: Orbit,
  outdent: Outdent,
  "paint-bucket": PaintBucket,
  paintbrush: Paintbrush,
  parentheses: Parentheses,
  "parking-circle": ParkingCircle,
  "parking-square": ParkingSquare,
  "party-popper": PartyPopper,
  "pause-circle": PauseCircle,
  "paw-print": PawPrint,
  "pc-case": PcCase,
  pen: Pen,
  "pen-square": PenSquare,
  "pencil-line": PencilLine,
  percent: Percent,
  "person-standing": PersonStanding,
  "phone-call": PhoneCall,
  "phone-forwarded": PhoneForwarded,
  "phone-incoming": PhoneIncoming,
  "phone-missed": PhoneMissed,
  "phone-off": PhoneOff,
  "phone-outgoing": PhoneOutgoing,
  pi: Pi,
  "picture-in-picture": PictureInPicture,
  "picture-in-picture-2": PictureInPicture2,
  "piggy-bank": PiggyBank,
  pilcrow: Pilcrow,
  pill: Pill,
  "pin-off": PinOff,
  pipette: Pipette,
  plane: Plane,
  "plane-landing": PlaneLanding,
  "plane-takeoff": PlaneTakeoff,
  "play-circle": PlayCircle,
  plug: Plug,
  "plug-2": Plug2,
  podcast: Podcast,
  pointer: Pointer,
  popcorn: Popcorn,
  popsicle: Popsicle,
  "pound-sterling": PoundSterling,
  power: Power,
  "power-off": PowerOff,
  printer: Printer,
  projector: Projector,
  puzzle: Puzzle,
  "qr-code": QrCode,
  quote: Quote,
  radar: Radar,
  radiation: Radiation,
  radical: Radical,
  radio: Radio,
  "radio-receiver": RadioReceiver,
  "radio-tower": RadioTower,
  rainbow: Rainbow,
  rat: Rat,
  receipt: Receipt,
  "rectangle-horizontal": RectangleHorizontal,
  "rectangle-vertical": RectangleVertical,
  recycle: Recycle,
  redo: Redo,
  "redo-2": Redo2,
  "refresh-ccw": RefreshCcw,
  "refresh-cw": RefreshCw,
  refrigerator: Refrigerator,
  regex: Regex,
  "remove-formatting": RemoveFormatting,
  repeat: Repeat,
  "repeat-1": Repeat1,
  replace: Replace,
  reply: Reply,
  "reply-all": ReplyAll,
  rewind: Rewind,
  ribbon: Ribbon,
  "rocking-chair": RockingChair,
  "roller-coaster": RollerCoaster,
  "rotate-3d": Rotate3d,
  "rotate-ccw": RotateCcw,
  "rotate-cw": RotateCw,
  route: Route,
  router: Router,
  rss: Rss,
  "russian-ruble": RussianRuble,
  sailboat: Sailboat,
  salad: Salad,
  sandwich: Sandwich,
  satellite: Satellite,
  "satellite-dish": SatelliteDish,
  scale: Scale,
  "scale-3d": Scale3d,
  scaling: Scaling,
  scan: Scan,
  "scan-face": ScanFace,
  "scan-line": ScanLine,
  school: School,
  "scissors-line-dashed": ScissorsLineDashed,
  "screen-share": ScreenShare,
  scroll: Scroll,
  "search-check": SearchCheck,
  "search-code": SearchCode,
  "search-slash": SearchSlash,
  server: Server,
  "server-cog": ServerCog,
  "server-crash": ServerCrash,
  "server-off": ServerOff,
  shapes: Shapes,
  share: Share,
  sheet: Sheet,
  shell: Shell,
  ship: Ship,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  shovel: Shovel,
  "shower-head": ShowerHead,
  shrink: Shrink,
  shrub: Shrub,
  shuffle: Shuffle,
  sigma: Sigma,
  signal: Signal,
  "signal-high": SignalHigh,
  "signal-low": SignalLow,
  "signal-medium": SignalMedium,
  "signal-zero": SignalZero,
  siren: Siren,
  "skip-back": SkipBack,
  "skip-forward": SkipForward,
  skull: Skull,
  slice: Slice,
  "sliders-horizontal": SlidersHorizontal,
  smile: Smile,
  "smile-plus": SmilePlus,
  snowflake: Snowflake,
  sofa: Sofa,
  "sort-asc": SortAsc,
  "sort-desc": SortDesc,
  space: Space,
  sparkles: Sparkles,
  "spell-check": SpellCheck,
  sprout: Sprout,
  square: Square,
  stamp: Stamp,
  "star-half": StarHalf,
  "step-back": StepBack,
  "step-forward": StepForward,
  stethoscope: Stethoscope,
  sticker: Sticker,
  "sticky-note": StickyNote,
  "stop-circle": StopCircle,
  store: Store,
  "stretch-horizontal": StretchHorizontal,
  "stretch-vertical": StretchVertical,
  strikethrough: Strikethrough,
  subscript: Subscript,
  "sun-dim": SunDim,
  "sun-medium": SunMedium,
  "sun-moon": SunMoon,
  sunrise: Sunrise,
  sunset: Sunset,
  superscript: Superscript,
  "swiss-franc": SwissFranc,
  "switch-camera": SwitchCamera,
  sword: Sword,
  swords: Swords,
  syringe: Syringe,
  "table-2": Table2,
  "table-properties": TableProperties,
  tablet: Tablet,
  tablets: Tablets,
  "tally-1": Tally1,
  "tally-2": Tally2,
  "tally-3": Tally3,
  "tally-4": Tally4,
  "tally-5": Tally5,
  tangent: Tangent,
  telescope: Telescope,
  tent: Tent,
  "test-tube": TestTube,
  "test-tube-2": TestTube2,
  thermometer: Thermometer,
  "thermometer-snowflake": ThermometerSnowflake,
  "thermometer-sun": ThermometerSun,
  timer: Timer,
  "timer-off": TimerOff,
  "timer-reset": TimerReset,
  "toggle-left": ToggleLeft,
  "toggle-right": ToggleRight,
  tornado: Tornado,
  touchpad: Touchpad,
  "touchpad-off": TouchpadOff,
  "tower-control": TowerControl,
  "toy-brick": ToyBrick,
  tractor: Tractor,
  "traffic-cone": TrafficCone,
  train: Train,
  "tram-front": TramFront,
  "trending-down": TrendingDown,
  "trending-up": TrendingUp,
  triangle: Triangle,
  trophy: Trophy,
  tv: Tv,
  "tv-2": Tv2,
  type: Type,
  umbrella: Umbrella,
  underline: Underline,
  undo: Undo,
  "undo-2": Undo2,
  unlink: Unlink,
  unlock: Unlock,
  "upload-cloud": UploadCloud,
  usb: Usb,
  utensils: Utensils,
  "utensils-crossed": UtensilsCrossed,
  "utility-pole": UtilityPole,
  variable: Variable,
  vegan: Vegan,
  vibrate: Vibrate,
  "video-off": VideoOff,
  view: View,
  voicemail: Voicemail,
  volume: Volume,
  "volume-1": Volume1,
  "volume-x": VolumeX,
  wallet: Wallet,
  wallpaper: Wallpaper,
  warehouse: Warehouse,
  watch: Watch,
  waves: Waves,
  webcam: Webcam,
  webhook: Webhook,
  wheat: Wheat,
  "whole-word": WholeWord,
  wifi: Wifi,
  "wifi-off": WifiOff,
  wind: Wind,
  wine: Wine,
  workflow: Workflow,
  "wrap-text": WrapText,
  "zoom-out": ZoomOut,
} as const;

interface HeroSectionProps {
  data?: HomeHeroSection;
  metricsData?: HomeKeyMetricsSection;
}

const HeroSection = ({ data, metricsData }: HeroSectionProps) => {
  const content = data ?? DEFAULT_HOME_PAGE_SETTINGS.sections.hero;

  return (
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden py-20 md:py-24">
      {/* Background */}
      <div className="absolute inset-0">
        <div className="hero-glow top-24 -left-32" />
        <div className="absolute top-20 right-[-10rem] w-[28rem] h-[28rem] rounded-full bg-primary/7 blur-3xl" />
        <div className="absolute inset-0 bg-[radial-gradient(circle_at_top,rgba(239,68,68,0.09),transparent_45%)]" />
        <div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-secondary/30" />
      </div>

      <div className="container-narrow relative z-10 w-full px-4 sm:px-6">
        <div className="grid lg:grid-cols-2 gap-12 lg:gap-16 items-center">
          {/* LEFT SIDE */}
          <div className="min-w-0">
            <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full border border-primary/35 mb-6">
              <span className="w-2 h-2 bg-primary rounded-full animate-pulse" />
              <span className="text-sm font-medium text-primary">
                {content.badge}
              </span>
            </div>

            <h1 className="text-4xl sm:text-5xl md:text-6xl lg:text-7xl font-bold leading-[1.05] tracking-tight mb-6">
              <span className="text-foreground">{content.title_line_1}</span>
              <br />
              <span className="text-gradient-primary">
                {content.title_line_2}
              </span>
            </h1>

            <p className="text-lg md:text-xl text-muted-foreground/95 mb-8 leading-relaxed max-w-xl">
              {content.description}
            </p>

            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                to={content.primary_href}
                className="btn-primary inline-flex items-center justify-center gap-2 group min-w-[210px]"
              >
                {content.primary_label}
                <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </Link>

              <Link
                to={content.secondary_href}
                className="btn-outline inline-flex items-center justify-center gap-2 min-w-[230px]"
              >
                <Play className="w-5 h-5" />
                {content.secondary_label}
              </Link>
            </div>

            <HeroSoftwareStrip data={content.software_strip} />
          </div>

          {/* RIGHT SIDE */}
          <div className="relative">
            <div className="border border-neutral-400/40 dark:border-white/10 rounded-3xl p-6 md:p-8 bg-white/5 dark:bg-transparent backdrop-blur-sm">
              <div className="flex flex-col divide-y divide-neutral-400/40 dark:divide-white/10">
                {content.cards.map((service) => {
                  const Icon =
                    iconMap[service.icon as keyof typeof iconMap] ??
                    FileText;

                  return (
                    <Link
                      key={service.id}
                      to={service.link}
                      className="flex items-start gap-4 py-4 hover:translate-x-1 transition-all duration-300 group"
                    >
                      {/* Icon */}
                      <div className="w-10 h-10 rounded-xl flex items-center justify-center border border-neutral-400/40 dark:border-white/10 group-hover:border-primary/60 transition-all duration-300">
                        <Icon className="w-5 h-5 text-primary" />
                      </div>

                      {/* Text */}
                      <div>
                        <h3 className="text-sm font-semibold text-foreground group-hover:text-primary transition-colors duration-200">
                          {service.title}
                        </h3>
                        <p className="text-sm text-muted-foreground">
                          {service.description}
                        </p>
                      </div>
                    </Link>
                  );
                })}
              </div>
            </div>
          </div>
        </div>

        <HomeMetricsSection
          data={metricsData}
          className="mt-14 sm:mt-16 lg:mt-20"
        />
      </div>
    </section>
  );
};

export default HeroSection;